### ISSUE TITLE
Text overflows on the crusader war popup

### ISSUE THREAD

**Issue by keichi2** [matanki-saito/CK2JPModCore#3]
![20190320011734_1](https://user-images.githubusercontent.com/3328615/54696652-8e28c380-4b6f-11e9-8a21-3012fa56ea6d.jpg)

文字を小さくするか、「カトリックの」を削るか、「エルサレムに対する」を削るかなどの対処がありそうです。

**Comment by matanki-saito** [comment]
guiを調整して修正したい

**Comment by matanki-saito** [comment]
スタートの年代を1095年（史実の第一次十字軍）にして一年くらい進めれば発生する

**Comment by matanki-saito** [comment]
![image](https://user-images.githubusercontent.com/35730970/57531455-79e59380-7374-11e9-9ff7-08e4fd2a53a5.png)

**Comment by matanki-saito** [comment]
![image](https://user-images.githubusercontent.com/35730970/57531477-8b2ea000-7374-11e9-9b45-e741c219db1a.png)

**Comment by matanki-saito** [comment]
文字を小さくしました
![image](https://user-images.githubusercontent.com/35730970/57532200-26744500-7376-11e9-91df-7d52c245d9df.png)
